services:

  db:
    image: postgres:17
    container_name: url-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: urlshortener
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: url-backend
    ports:
      - "8080:8080"
    env_file:
      - .env.dev
    depends_on:
      - db

volumes:
  pgdata: