spring.application.name=url_shortener
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb
spring.jpa.hibernate.ddl-auto=update

# base URL for generated links
app.base-url=http://localhost:8080